import './globals.css'
import { RootProvider } from '@/app/store/root.context'
import { Carter_One } from 'next/font/google'
import React from 'react'

const inter = Carter_One({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Exy Shirt',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
